apiVersion: v1
kind: Service
metadata:
  name: ss-mongo
  namespace: ss-m2
spec:
  type: ClusterIP
  selector:
    app: ss-mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: ss-api
  namespace: ss-m2
spec:
  type: ClusterIP
  selector:
    app: ss-api
  ports:
    - name: http
      port: 3000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: ss-frontend
  namespace: ss-m2
spec:
  type: ClusterIP
  selector:
    app: ss-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
